import { useState, useEffect } from "react"
import { HeaderDemo } from "@/components/Header/HeaderDemo"
import { Header } from "@/components/Header/Header"
import { BlueBackground } from "@/components/topBar/BlueBackground"
import { WhiteContainer } from "@/components/White-Container"
import { StudentFeedback } from "@/components/feedbacks/StudentFeedback"
import { FeedbackList } from "@/components/feedbacks/FeedbackList"
import { FeedbackTitle } from "@/components/topBar/FeedbackTitle"
import { useUser } from "../UserProvider"
import { Loading} from "@/components/Loading"
import SearchBar from "@/components/inputs/SearchBar"